### ISSUE TITLE
How to restore page scroll when using scrollable modal?  [fixed in 1.3.8]

### ISSUE THREAD

**Issue by mvkasatkin** [euvl/vue-js-modal#148] opened 2017-12-11 12:26 UTC
Hi! Is it possible to restore page scroll when modal with scrollable enabled property closed? It seems that the modal resets page scroll to 0 when it opens in scrollable mode. Without scrollable=true it's ok, page scroll is not affected.

**Comment by simboonlong** [comment] 2017-12-15 07:38
Yes, I am encountering this too, after I've bumped up the version from 1.3.4 to 1.3.6.

**Comment by dmydry** [comment] 2017-12-20 23:00
+1 guys, a little annoying, hope it will be fixed soon

**Comment by lostan** [comment] 2017-12-23 23:55
+1, hope it will be fixed soon

**Comment by euvl** [comment] 2017-12-27 11:57
so may people complained and not a single PR 😄 👍 👍 👍

**Comment by ingria** [comment] 2018-01-04 02:14
Seems like this will be impossible unless the modal is created as direct `<body>` child. Also this will fix #134

**Comment by mvkasatkin** [comment] 2018-01-04 03:28
@ingria, #134 looks like absolutely different issue. I have no troubles with overlays and I cannot imagine how can I fix page scroll by z-index?

**Comment by ingria** [comment] 2018-01-04 03:52
Not with z-index, but with modal created in `<body>`. Then it will be possible to create fixed container that will not alter page scroll at all.

About #134. Imagine your app has such markup:
```
body
 - header  -> fixed, z-index:100
 - content -> z-index: 50
 - - modal -> inherits z-index: 50
```
In this setup header will be displayed above the modal. Creating a modal into the root node (`body`) allows to set `z-index` to whatever value you want.

Like this:
```
body
 - modal   -> z-index: 9000
 - header  -> fixed, z-index:100
 - content -> z-index: 50
```

**Comment by mvkasatkin** [comment] 2018-01-04 06:18
@ingria Yes, this workaround works well. But it would be very nice not to touch (or save and restore) page scroll in case of component with nested modal and not violate an independent context, taking the modal form out of it.

**Comment by euvl** [comment] 2018-01-04 11:46
Hey guys, the problem is that some people previously asked to fix the page scroll when `scrollable=` even though i didn't want to modify `body` class that was the only was to do it. 

Take a look in Modal.vue css, probably you will be able redefine `position:fixed` that is applied to body with `position:relative !important` or something like that.

**Comment by mvkasatkin** [comment] 2018-01-04 14:07
@euvl thank you! `position: relative` on `body` solves the problem

**Comment by euvl** [comment] 2018-01-12 09:53
I think it should work now (after i've changed position: fixed => position:absolute).
Lemme know if it does.

**Comment by sebbler1337** [comment] 2018-01-12 11:11
Works for me, thanks a lot!

**Comment by euvl** [comment] 2018-01-12 11:32
@sebbler1337 no worries at all 👍

**Comment by shpfive** [comment] 2018-02-02 14:52
there is another Problem with page scroll restore:

just a modal with height:auto and scrollable:true
if you doubleclick the background before Modal is closed the page scroll gets restored and disabled again.

https://v351k6x350.codesandbox.io/
https://v351k6x350.codesandbox.io/

**Comment by Kxtreme** [comment] 2018-02-06 00:19
to atenuate the problem I put the tag on the modal @closed="close"
and in the code
close() {
      document.body.classList.remove("v--modal-block-scroll")
}
kind of works.

**Comment by Emirii** [comment] 2018-02-16 15:17
Hi there, I have the same issue on version 1.3.10. 

When I click on the modal half way down the page, the page scroll jumps to the top when the modal opens. When the modal closes the user is still on the top of the page. 

Here's my modal settings (it does it on both scrollable true or false):
```
<vue-modal width="350" height="auto" :scrollable="true" name="myModal">
<vue-modal width="350" height="auto" :scrollable="false" name="myModal">
```

I tried setting `.v--modal-block-scroll` to `position: relative !important` but it did not make a difference. 

Maybe I am missing something important? Thank you!

**Comment by Kxtreme** [comment] 2018-02-16 15:33
I am trying to replicate your issue without success it is working fine so here is my modal code see if it helps:
<modal name="client-modal" height="auto" :scrollable="true" :clickToClose="false" @closed="close">
            <div slot="top-right">
                <button class="round-button" @click="$modal.hide('client-modal')">❌</button>
                <br v-if="isViewingJob || isEditingJob || isEditingPayment">
                <button v-if="isViewingJob || isEditingJob || isEditingPayment" class="round-button" @click="back">&#9664;</button>
                <br v-if="isEditingJob || isEditingPayment">
                <button class="round-button" v-if="isEditingJob || isEditingPayment" @click="save">&#128190;</button>
                <br v-if="!isEditingJob && !isEditingPayment && !isViewingJob">
                <button class="round-button" v-if="!isEditingJob && !isEditingPayment && !isViewingJob" @click="send">	{{(sending ? '&#9676;' : (concludeSending ? '&#10003;' : '&#9993;'))}}</button>

            </div>
            <loading v-if="loading"></loading>
            <clientview v-show="!loading" :client="clientManaging" :permission="permission" :save="saving" :cancel="cancel" v-if="isViewingClient" :isViewingJob="isViewingJob" :isEditingJob="isEditingJob" :isEditingPayment="isEditingPayment" @loaded="loaded" @jobLoadedForViewing="jobLoadedForViewing" @saved="savedEditedJob" @jobLoadedForEditing="jobLoadedForEditing" @paymentLoadedForEditing="paymentLoadedForEditing"></clientview>
        </modal>

**Comment by DreaMinder** [comment] 2018-02-16 17:04
I have same issue but only with touchscreens If I tap on modal bg, scrollbar disapears. Browser chrome desktop or mobile. Latest lib version.
For reproduction, use "partnership inquiry" button on this page https://module-5.com/en/service/ig

**Closed** 2018-03-25 17:02 UTC
Labels: answered, question
